---
title: "Summer of Data - Data Publishing"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: default
    number_sections: no
    self_contained: no
    toc: no
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r source-libraries, include=FALSE}
source("libraries.R")
```

<hr> 

```{r read-files, include=FALSE}
judge_master <-
  readr::read_csv("../data/final-files-nluo/judges_master_file.csv",
                  col_types = cols(.default = "c"))

total_judges_per_court <- table(judge_master$fileTitle) %>% data.frame() %>% arrange(desc(Freq))
names(total_judges_per_court) <- c("Court", "Total Judges")

```

#### Download Files

1. [Master file of Judges](https://raw.githubusercontent.com/justicehub-in/summer-of-data-chapter-1/main/data/final-files-nluo/judges_master_file.csv) _(Right click > Save link as)_

2. [State level files](https://github.com/justicehub-in/summer-of-data-chapter-1/tree/main/data/final-files-nluo/csv)
_(Click on File > Click on Raw > Right click > Save link as)_

<hr> 

#### Total Judges

Profile details available for **`r nrow(judge_master)` judges** across  **`r  unique(judge_master$fileTitle) %>% length()`  courts**

```{r total-judges-per-court, echo=FALSE}
DT::datatable(
  total_judges_per_court,
  filter = 'top',
  options = list(autoWidth = TRUE)
)
```
